### ISSUE TITLE
Safari version

### ISSUE THREAD

**Issue by bart-kneepkens** [twstokes/herpderp#1]
Why is the Safari version of this plugin 'retired'?

Are there plans for development?

**Comment by twstokes** [comment]
It probably broke at some point and wasn't worth the effort to maintain since desktop Safari has a low market share.

I don't plan on developing it again but encourage a PR if someone wants to contribute.

**Comment by bart-kneepkens** [comment]
Please see my [PR](https://github.com/twstokes/herpderp/pull/2).

It's working again, but I have no way of building into a valid `.safariextz` file.

**Comment by twstokes** [comment]
Great! I'll check it out soon.
