### ISSUE TITLE
Doesn't do anything as of Youtube redesign circa Aug 30, 2017.

### ISSUE THREAD

**Issue by christian-mann** [twstokes/herpderp#5]
Youtube uses (non-unique) IDs instead of classes to mark comment text, so the selector doesn't find anything.

I suspect this is the same on all platforms, but I'm testing on **Version 60.0.3112.90 (Official Build) (64-bit)**

Screenshot of comment DOM: The `id="content-text"` used to be `class="content-text"`.
<img width="556" alt="screen shot 2017-08-30 at 9 19 41 pm" src="https://user-images.githubusercontent.com/1406124/29901956-181ed400-8dc9-11e7-9c45-05c7c40b81c3.png">

**Comment by twstokes** [comment]
Yep, you're right. Thanks.

**Comment by twstokes** [comment]
59e4d4b1a73a038269c86433b316de1d5e85c04b seems to fix... I'll push out the update now.
