### ISSUE TITLE
Not working on firefox

### ISSUE THREAD

**Issue by Gotos** [twstokes/herpderp#9]
Hi there!

Since the latest update of the YouTube layout HerpDerp isn't working on Firefox anymore. At least not the version from the Firefox addon website.
I guess this is related to commit 59e4d4b1a73a038269c86433b316de1d5e85c04b and issue #6? Would it be possible to first fix this for Firefox too and then convert the code to WebExtensions? I see that you linked to an article about converting chrome plugins to WebExtensions in Issue #6 so I guess that is the way you want to develop this awesome plugin in the future, but a quick (and possibly dirty) hack to let Firefox users enjoy YouTube without those nasty comments would be highly appreciated!

Thanks in advance!

**Comment by twstokes** [comment]
You're totally right, and the FF fix has been in the back of my mind since it broke. I'm also finding that the Chrome fix isn't 100% working (initial page loads work, but subsequent loads append comments to herp derps). I hope to be able to get to this soon, sorry for the inconvenience.

**Comment by twstokes** [comment]
Latest version (1.6.3) uploaded to Mozilla Add-ons.
